2.42. Разметка всех страниц
htmlacademy-htmlcss/2302197-sedona-36 pull request #2
Opened 2023-01-23 22:06 UTC by Developer2220

2023-01-25 12:20 UTC, Kartaviy-arteom requested changes

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +      <section class="filtercontent">
в наименовании класса упустил разделитель

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +        </header>
этот header тут не имеет смысла, можно просто оставить заголовок

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +        <form class="catalog-filter" action="#" method="get">
форму тебе нужно будет переместить в первую секцию. Можно использовать action из курса, чтобы проверить, что форма рабочая

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +      <section class="view">
это кнопки, по клику просто добавится класс списку, и изменится отображение карточек

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +          <a class="product-card-link" href="#">
лучше обернуть в ссылку отдельно картинку и отдельно заголовок. Или в одну ссылку заголовок и картинку, без цены

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +            <p>Гостиница</p>
не нужно одно слово оборачивать в <p>

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +        <label for="subscription-email" class="visually-hidden">Ваш e-mail</label>
тут нужна форма

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +        <button class="button-subscription">Подписаться</button>
у кнопки будет тип submit

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +      <h9 class="visually-hidden">Социальные сети</h9>
уровень заголовка (вообще они h1-h6)

2023-01-25 12:20 UTC, Kartaviy-arteom commented on catalog.html
> +          <a class="button" href="https:/www.youtube.com/user/htmlacademyru">
невалидный href

2023-01-25 12:20 UTC, Kartaviy-arteom commented on index.html
> +        <img class="welcome" src="" alt="Приветствие»">
оставь один img, остальные не нужны

2023-01-25 12:20 UTC, Kartaviy-arteom commented on index.html
> +        <img class="index-background" src="" alt="Обзорный вид">
тут не нужен img

2023-01-25 12:20 UTC, Kartaviy-arteom commented on index.html
> +      <section class="advantages">
причины должна быть в предыдущей секции

2023-01-25 12:20 UTC, Kartaviy-arteom commented on index.html
> +      <section class="advantages-icon">
Вот это одна секция
index-background - лишнее

2023-01-25 12:20 UTC, Kartaviy-arteom commented on index.html
> +            <h6 class="advantages-title">Жильё</h6>
тут не будет h6

2023-01-25 12:20 UTC, Kartaviy-arteom commented on index.html
> +          <h8>Подпишитесь на рассылку</h8>
h8 и нужна форма

2023-01-25 12:20 UTC, Kartaviy-arteom commented on index.html
> +      <h9 class="visually-hidden">Социальные сети</h9>
так же как в каталоге

2023-01-28 10:00 UTC, Kartaviy-arteom requested changes

2023-01-28 10:00 UTC, Kartaviy-arteom commented on catalog.html
> +          </ul>
тебе не нужно помещать "хлебные крошки" в форму

2023-01-28 10:00 UTC, Kartaviy-arteom commented on catalog.html
> +
что-то тут ты напутал. Ты открыл секцию, открыл форму, закрыл секцию, а форму продолжешь, так это не работает

2023-01-28 10:00 UTC, Kartaviy-arteom commented on catalog.html
> +        <button type="button" class="button button-dark">
Здесь у тебя лишние секции для видов и для селекта

2023-01-28 10:00 UTC, Kartaviy-arteom commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru/">
action и method

2023-01-28 10:00 UTC, Kartaviy-arteom commented on catalog.html
> +      <h5 class="visually-hidden">Социальные сети</h5>
почему получился h5?

2023-01-28 10:00 UTC, Kartaviy-arteom commented on index.html
> +        <h3 class="visually-hidden">Причины</h3>
объедим с предыдущей

2023-01-28 10:00 UTC, Kartaviy-arteom commented on index.html
> +          <form action="https://echo.htmlacademy.ru/">
сначала идет заголовок, потом параграф, потом форма

2023-01-28 12:39 UTC, Developer2220 commented on catalog.html
> +          </ul>
Ок. Вынес в следующую секцию

2023-01-28 12:45 UTC, Developer2220 commented on catalog.html
> +
Перенес форму из хлебных крошек во вторую секцию, посмотри теперь будет верно. Вроде теперь так открываю секцию -  открываю форму-  закрываю форму закрываю секцию

2023-01-28 12:51 UTC, Developer2220 commented on catalog.html
> +        <button type="button" class="button button-dark">
Правильно понимаю что ты имеешь ввиду, что <section class="catalog"> заканчивается после пагинации, если так то исправлю

2023-01-28 12:54 UTC, Developer2220 commented on catalog.html
> +        <form action="https://echo.htmlacademy.ru/">
добавил method

2023-01-28 12:56 UTC, Developer2220 commented on catalog.html
> +      <h5 class="visually-hidden">Социальные сети</h5>
Исправил на h3

2023-01-28 12:57 UTC, Developer2220 commented on index.html
> +          <form action="https://echo.htmlacademy.ru/">
ОК. исправил

2023-01-29 11:11 UTC, Kartaviy-arteom approved these changes

2023-01-29 11:11 UTC, Kartaviy-arteom commented on catalog.html
> +            <a class="breadcrumbs-link"><img src="#" alt="Гостиницы">Гостиницы</a>
section отдельно для заголовка и хлебных крошек тебе не к чему. https://doka.guide/html/section/

2023-01-29 11:11 UTC, Kartaviy-arteom commented on catalog.html
> +          </div>
потом так же fieldset c label будет

2023-01-29 11:11 UTC, merged