Декоративные элементы всех страниц
htmlacademy-htmlcss/2302197-sedona-36 pull request #7
Opened 2023-03-08 22:34 UTC by Developer2220

---
:mortar_board: [Декоративные элементы всех страниц](https://up.htmlacademy.ru/htmlcss/36/user/2302197/tasks/16)

2023-03-11 10:55 UTC, Kartaviy-arteom requested changes
футер ломается при наполнении соцсетями

2023-03-11 10:55 UTC, Kartaviy-arteom commented on styles/styles.css
> +  width: 1280px;
тут замени width: 1280px; на min-width: 1280px

2023-03-11 10:55 UTC, Kartaviy-arteom commented on styles/styles.css
> +.footer-social-item .button {
тут ссылки выпадаюь из li, так как они больше родителя. такого быть не должно

2023-03-11 10:55 UTC, Kartaviy-arteom commented on styles/styles.css
>    color: #333333;
.view-list ломается при переполнении

2023-03-11 10:55 UTC, Kartaviy-arteom commented on styles/styles.css
> +  padding: 0;
нужно звезды выровнять

2023-03-11 10:55 UTC, Kartaviy-arteom commented on styles/styles.css
> +.breadcrumbs-item {
тут нет списка из 3 элементов, стрелка это псевдоэлемент одного их пунктов

2023-03-11 10:55 UTC, Kartaviy-arteom commented on styles/styles.css
> +  position: relative;
размер элемента, тут используется box-sizing:content-box и элемент выпадает из body

2023-03-11 10:55 UTC, Kartaviy-arteom commented on index.html
> +    <div class="body-container">
хедер нужно исправить, при таком решении ломается при переполнении

2023-03-13 22:13 UTC, Developer2220 commented on styles/styles.css
> +  width: 1280px;
ок

2023-03-13 22:14 UTC, Developer2220 commented on styles/styles.css
> +.footer-social-item .button {
добавил ссылкам display:block

2023-03-13 22:15 UTC, Developer2220 commented on styles/styles.css
>    color: #333333;
добавил max-width

2023-03-13 22:19 UTC, Developer2220 commented on styles/styles.css
> +  padding: 0;
добавил margin-right

2023-03-14 06:16 UTC, Kartaviy-arteom requested changes
еще фавиконка нужна

2023-03-14 06:16 UTC, Kartaviy-arteom commented on index.html
> +                <svg class="modal-calendar" width="16" height="15" viewBox="0 0 16 15" fill="none"
эту свг нужно вынести в фоны

2023-03-14 06:16 UTC, Kartaviy-arteom commented on index.html
> +                <svg class="departure-calendar" width="16" height="15" viewBox="0 0 16 15" fill="none"
и эту в фоны

2023-03-14 06:16 UTC, Kartaviy-arteom commented on styles/styles.css
> +.modal-title {
нужно ограничить ширину, чтобы текст не налазил на кнопку

2023-03-14 06:16 UTC, Kartaviy-arteom commented on styles/styles.css
> +.modal {
нужен еще общий оверлей

2023-03-14 06:16 UTC, Kartaviy-arteom commented on styles/styles.css
> +.tooltip-text {
у него еще должен быть треугольник сверху

2023-03-14 06:16 UTC, Kartaviy-arteom commented on styles/styles.css
> +  background-image: url(../images/modal-tooltip-rectangle.svg);
этого файла нет

2023-03-14 19:14 UTC, Developer2220 commented on styles/styles.css
> +  padding: 0;
добавил вертикальное центрирование

2023-03-14 19:42 UTC, Developer2220 commented on styles/styles.css
> +.breadcrumbs-item {
Добавил как псевдоэлемент первому элементу и заодно добавил состояние первому элементу

2023-03-14 19:50 UTC, Developer2220 commented on styles/styles.css
> +  position: relative;
добавил  box-sizing: border-box

2023-03-14 20:03 UTC, Developer2220 commented on styles/styles.css
> +.modal {
задал верный фоновый цвет

2023-03-14 20:07 UTC, Developer2220 commented on styles/styles.css
> +  background-image: url(../images/modal-tooltip-rectangle.svg);
удалил код из CSS и удалил эту SVG

2023-03-14 20:15 UTC, Developer2220 commented on styles/styles.css
> +.modal-title {
добавил max-width

2023-03-14 20:45 UTC, Developer2220 commented on index.html
> +                <svg class="modal-calendar" width="16" height="15" viewBox="0 0 16 15" fill="none"
исправил

2023-03-14 20:45 UTC, Developer2220 commented on index.html
> +                <svg class="departure-calendar" width="16" height="15" viewBox="0 0 16 15" fill="none"
исправил

2023-03-14 20:57 UTC, Developer2220 commented on styles/styles.css
> +.tooltip-text {
добавил

2023-03-15 11:03 UTC, merged